In [1]:
import requests 
import pandas as pd 
from tqdm import tqdm
from bs4 import BeautifulSoup

In [2]:
data = []

for page in tqdm(range(1, 11)):
    link = 'https://quotes.toscrape.com/page/' + str(page)
    res = requests.get(link)
    soup = BeautifulSoup(res.text , 'html.parser')

    for sp in soup.find_all('div', class_ = 'quote'):
    
        quote      = sp.find('span' , class_ = 'text').text
        author     = sp.find('small').text
        author_id  = sp.find('a').get('href')

        tags = []
        for tag in sp.find_all('a' , class_ = 'tag'):
            tags.append(tag.text)
    
        tags       = ','.join(tags)
    
        data.append([quote , author , author_id , tags])

100%|██████████| 10/10 [00:11<00:00,  1.16s/it]

In [3]:
df = pd.DataFrame(data , columns = ['quotes' , 'author' , 'author_id' , 'tags'])

In [4]:
df.head()

,quotes,author,author_id,tags
0,“The world as we have created it is a process ...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices"
2,“There are only two ways to live your life. On...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational"

In [5]:
df['author_link'] = 'https://quotes.toscrape.com' + df['author_id']

In [6]:
df.head()

,quotes,author,author_id,tags,author_link
0,“The world as we have created it is a process ...,Albert Einstein,/author/Albert-Einstein,"change,deep-thoughts,thinking,world",https://quotes.toscrape.com/author/Albert-Eins...
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,/author/J-K-Rowling,"abilities,choices",https://quotes.toscrape.com/author/J-K-Rowling
2,“There are only two ways to live your life. On...,Albert Einstein,/author/Albert-Einstein,"inspirational,life,live,miracle,miracles",https://quotes.toscrape.com/author/Albert-Eins...
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,/author/Jane-Austen,"aliteracy,books,classic,humor",https://quotes.toscrape.com/author/Jane-Austen
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,/author/Marilyn-Monroe,"be-yourself,inspirational",https://quotes.toscrape.com/author/Marilyn-Monroe

In [7]:
df.to_csv('Quotes.csv' , index = False)