In [6]:
import pandas as pd 

df_1 = pd.read_csv('books.csv')
df_2 = pd.read_csv('data.csv')

In [8]:
df_1.head()

,title,rating,price,stock,book_link,img_link
0,A Light in the Attic,Three,51.77,In stock,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/../media/cache/2c/d...
1,Tipping the Velvet,One,53.74,In stock,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/../media/cache/26/0...
2,Soumission,One,50.10,In stock,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/../media/cache/3e/e...
3,Sharp Objects,Four,47.82,In stock,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/../media/cache/32/5...
4,Sapiens: A Brief History of Humankind,Five,54.23,In stock,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/../media/cache/be/a...

In [10]:
df_2.head()

,category,price_e_tax,price_i_tax,tax,quantity,upc,reviews
0,Poetry,51.77,51.77,Â£0.00,In stock (22 available),a897fe39b1053632,0
1,Historical Fiction,53.74,53.74,Â£0.00,In stock (20 available),90fa61229261140a,0
2,Fiction,50.10,50.10,Â£0.00,In stock (20 available),6957f44c3847a760,0
3,Mystery,47.82,47.82,Â£0.00,In stock (20 available),e00eb4fd7b871a48,0
4,History,54.23,54.23,Â£0.00,In stock (20 available),4165285e1663650f,0

#### Creating the New DataFrame

In [13]:
df = pd.DataFrame()

In [26]:
df['title']         = df_1['title']
df['upc']           = df_2['upc']
df['category']      = df_2['category']
df['price_e_tax']   = df_2['price_e_tax']
df['price_i_tax']   = df_2['price_i_tax']
df['tax']           = df_2['tax']
df['rating']        = df_1['rating']
df['reviews']       = df_2['reviews']
df['quantity']      = df_2['quantity']
df['stock']         = df_1['stock']
df['book_link']     = df_1['book_link']
df['img_link']      = df_1['img_link']

In [30]:
df.head()

,title,category,price_e_tax,price_i_tax,upc,tax,rating,reviews,quantity,stock,book_link,img_link
0,A Light in the Attic,Poetry,51.77,51.77,a897fe39b1053632,Â£0.00,Three,0,In stock (22 available),In stock,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/../media/cache/2c/d...
1,Tipping the Velvet,Historical Fiction,53.74,53.74,90fa61229261140a,Â£0.00,One,0,In stock (20 available),In stock,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/../media/cache/26/0...
2,Soumission,Fiction,50.10,50.10,6957f44c3847a760,Â£0.00,One,0,In stock (20 available),In stock,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/../media/cache/3e/e...
3,Sharp Objects,Mystery,47.82,47.82,e00eb4fd7b871a48,Â£0.00,Four,0,In stock (20 available),In stock,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/../media/cache/32/5...
4,Sapiens: A Brief History of Humankind,History,54.23,54.23,4165285e1663650f,Â£0.00,Five,0,In stock (20 available),In stock,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/../media/cache/be/a...

In [33]:
df.to_csv('Final_Scrap.csv' , index = False)